### ISSUE TITLE
Escape dots

### ISSUE THREAD

**Issue by ejb** [ejb/jargon-buster#1]
The regex is treating full stops (periods) in terms as operators. Need to escape them before running the regex. Otherwise you get [unfortunate matches like this](https://twitter.com/elliot_bentley/status/582289243319435264):

![cbsxranwqaedrjv png-large](https://cloud.githubusercontent.com/assets/1442752/6887810/4e838e4e-d662-11e4-9023-62bdac08f4af.png)

**Comment by jasonleefrench** [comment]
This should be fixed now - there's a handy function I sellotaped in that escapes strings for regex use. More explanation on what it's actually doing is [here](http://stackoverflow.com/a/6969486).

![rp4fc3492d](https://cloud.githubusercontent.com/assets/2090489/6890837/8cec3896-d6aa-11e4-8b23-72f3c812d08c.png)
